---
    - name: Join Domain
      win_domain_membership:
        dns_domain_name: "{{ domainname }}"
        domain_admin_user: "{{ DomainUser }}"
        domain_admin_password: "{{ DomainPassword }}"
        domain_ou_path: "{{ OU }}"
        state: domain
      register: domain_state
    - name: Reboot when required
      win_reboot:
      when: domain_state.reboot_required